# Auto-generated by BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/Users/lee/Desktop/Computer_Systems/Macos/KVM-Opencore/src/OpenCorePkg/UDK
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/Users/lee/Desktop/Computer_Systems/Macos/KVM-Opencore/src/OpenCorePkg/UDK/BaseTools
fi
if [ -e /Users/lee/Desktop/Computer_Systems/Macos/KVM-Opencore/src/OpenCorePkg/UDK/BaseTools/Bin/Darwin-x86_64 ]
then
  FOUND_TOOLS_PATH_BIN=0
  for DIR in $(echo $PATH | tr ':' ' '); do
    if [ "$DIR" = "/Users/lee/Desktop/Computer_Systems/Macos/KVM-Opencore/src/OpenCorePkg/UDK/BaseTools/Bin/Darwin-x86_64" ]; then
      FOUND_TOOLS_PATH_BIN=1
    fi
  done
  if [ $FOUND_TOOLS_PATH_BIN = 0 ]
  then
    export PATH=/Users/lee/Desktop/Computer_Systems/Macos/KVM-Opencore/src/OpenCorePkg/UDK/BaseTools/Bin/Darwin-x86_64:$PATH
  fi
fi
